### ISSUE TITLE
CBC android 

### ISSUE THREAD

**Issue by noob-eng** [yne/dzr#10]
how to get dzr-CBC for android?

**Comment by yne** [comment]
same as PC:
- find the key (using a desktop)
- put the key in your `.profile` (`export DZR_CBC=g4.............a1` )
- restart termux

**Comment by noob-eng** [comment]
yes I found 0*67] but I don't know how to. re-assemble it
can u help me .. 
[0x61, 0x39, 0x76, 0x30, 0x77, 0x35, 0x65, 0x67]
 [0x31, 0x6e, 0x66, 0x7a, 0x63, 0x38, 0x6c, 0x34]

**Comment by yne** [comment]
You are almost done.

I updated the [wiki](https://github.com/yne/dzr/wiki) instruction, I hope it's okay now.

**Comment by noob-eng** [comment]
thanks it worked
