### ISSUE TITLE
'which' from debianutils is deprecated and spams warnings

### ISSUE THREAD

**Issue by samoht0** [yne/dzr#12]
Using 'command -v' instead prevents this.
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1814961.html

The change should cause no issues with other distributions.

**Comment by yne** [comment]
Thanks for the heads up

```bash
command -v jq fake >/dev/null || echo missing # fail
which      jq fake >/dev/null || echo missing # work
```
I guess I'll have to iterate on every commands...

Are *BSDs and Android fine with this change ?

**Comment by samoht0** [comment]
Works on Android/Termux.
