### ISSUE TITLE
search by user

### ISSUE THREAD

**Issue by noob-eng** [yne/dzr#15]
search by user not work 
![Screenshot_20220207-194305](https://user-images.githubusercontent.com/80917132/152851705-8071af6d-d1e9-4771-8816-d2e29d918eb8.png)

**Comment by yne** [comment]
![IMG_20220208_082444](https://user-images.githubusercontent.com/5113053/152938109-9f80636d-3e90-4203-8f4b-aaf9d2f7a3dd.jpg)
works fine here.

what was your search query ?

what result did you expect ?

**Comment by noob-eng** [comment]
search query I put my user name on deezer
the result was getting playlist and others ..

**Comment by yne** [comment]
I need more info, for example the buggy username
so I can reproduce the bug.
