### ISSUE TITLE
[Feature request] Decryption proxy

### ISSUE THREAD

**Issue by freijon** [yne/dzr#16]
I would very much like to create playlists and use them in mpv (or any other player), maybe together with a tool like mpvc-ipc/mpvc.
That's why I came up with the idea to have a local "proxy" running that does all the decryption on the fly. You could put tracks in a local m3u playlist with a url like:
localhost:8080/1234565

if you request this URL you would get the decrypted data of /track/1234565.

`dzr` itself also could make use of this proxy and create a temporary playlist with the "play all tracks" feature instead of running `mpv` for each track.

I gave it a try but unfortunately my bash script skills are at a beginner level where it will take a lot of effort and probably will not meet your requirements.

What do you think about this?

**Comment by yne** [comment]
The first solution that comes in mind is to make `dzr` cgi compliant (by detecting `$QUERY_STRING`?)

This would allow to use dzr as an http endpoint ( localhost/cgi-bin/dzr?12345 ) using any generic http server like apache or nginx.

**Comment by freijon** [comment]
That's a nice approach that I didn't consider. I experimented with netcat (openbsd version) and used `nc -lkp 8080` and `grep` and `cut` GET requests to get the track ID and then work from there. Like this you only need netcat and not a webserver. But maybe it would be more complicated.

**Comment by yne** [comment]
Also note that multiple IDs are already supported:
```bash
dzr /track/6113114,806027
```
This has the advantage of reusing the same session token for all of them and avoid re-negotiating for every track

**Comment by yne** [comment]
Does the multiID example helped you to resolve your playlist use case ?

**Comment by freijon** [comment]
No, I don't have the knowledge to implement this, that's why I created a feature request issue instead of a pull request or a fork. I assumed this could be of general interest. It would make the app so much more powerful, something similar like [GMusic Proxy](https://gmusicproxy.github.io). You could not only use any player, you could even use different devices to play Deezer music. And as mentioned, you could create local playlists. It looks like a huge potential with acceptable(?) implementation effort for someone with the know-how to implement this. But unfortunately I don't have it ;)

**Comment by yne** [comment]
It is done.

See https://github.com/yne/dzr#as-cgi
