### ISSUE TITLE
Getting song's MD5

### ISSUE THREAD

**Issue by wabeha** [yne/dzr#2]
If I'm not mistaken, the method song.getListData does not give song's MD5 anymore breaking the script a little bit. Maybe there is an alternative way of getting it...

**Comment by yne** [comment]
The server is returning the MD5 just fine.

![image](https://user-images.githubusercontent.com/5113053/71990535-d5359180-3233-11ea-9885-5d5cd946c427.png)

Are you sure your `song.getListData` request was authenticated with a fresh SID ?

You can still use `dzr-db` to get the MD5 without being authenticated:
```
# assuming dzr binaries are in your $PATH
dzr-db 131421414 | xargs dzr | mpv -
```

**Comment by wabeha** [comment]
Thank you for the reply! Yes, the problem probably was that I was using a day old SID that was already expired. Using that, the server responded with completely sensible info about the song but the field MD5_ORIGIN was missing. Now I tried with a fresh SID as you suggested and MD5_ORIGIN was there. So this was a non-issue and I apologize for opening that.
All the best to you.
