### ISSUE TITLE
Question about CBC decryption

### ISSUE THREAD

**Issue by mariusklocke** [yne/dzr#24]
Hey there,

thank you for sharing your work on this project. This is not an actual issue, but rather a question on your code. I'm currently implementing a custom Deezer downloader in Node.js with ID3 tags and Premium Account support.

I took your bash implementation as a starting point and kinda got the most things, but i'm a little stuck with CBC decryption. I got the track key calculation right, but I'm struggling with block sizes. My decrypted files are only correct for the first 2048 bytes. I would really appreciate, if you could explain, what you are doing in the last loop [here](https://github.com/yne/dzr/blob/master/dzr-dec#L28)? I think the first line of `dd` into `openssl cf-cbc` is the actual decryption. But what is the second line for? What does the `grep` check for?

Greetings,
Marius

**Comment by yne** [comment]
> But what is the second line for?

The non-encrypted chunks

> What does the grep check for?

The end of the stream (empty dd copy)

**Comment by mariusklocke** [comment]
Cool, I think I got it! Thanks your help :wave:
