### ISSUE TITLE
Track token has no sufficient rights on requested media.

### ISSUE THREAD

**Issue by KagChi** [yne/dzr#28]
Seems like https://www.deezer.com/en/track/122016704 are not downloadable

**Comment by yne** [comment]
Works fine in France

can you play it from the web interface ?

**Comment by KagChi** [comment]
> can you play it from the web interface ?

If you mean official webplayer. yes (using premium account)

> Works fine in France

not working in Indonesia and United States

**Comment by yne** [comment]
if possible, can you try with a basic account ?

In any case I won't be able to help you if I cant reproduce here.

**Comment by KagChi** [comment]
Sorry, deezer free doesnt available in my country

**Comment by KagChi** [comment]
But, its does working on us. using basic account on their official webplayer.

**Comment by yne** [comment]
what are the `available_countries` value in https://api.deezer.com/track/122016704 from :us: & :indonesia: ?

**Comment by KagChi** [comment]
Same for me, only FR

**Comment by yne** [comment]
not a DZR related issue.

**Comment by yne** [comment]
do you have something in your mind @KagChi ?

**Comment by milos192** [comment]
Hey @yne, sorry to necro this, but I just wanted to ask: if a track has an empty array for `available_countries`, there's basically nothing that can be done?

https://api.deezer.com/track/1141396

**Comment by yne** [comment]
@milos192 nothing dzr can do in it actual form.
but the older deezer CDN e-cdn-proxy-0.deezer.com (which only require a static key per track) may still have the mp3 available and does not check for country or expire or account or quality

but thats just a "last-chance" solution.

**Comment by milos192** [comment]
Sorry @yne, I totally missed this reply. Thank you so much for the info!
