### ISSUE TITLE
Deezer Free will no longer be available in your country as of 23rd January 2023.

### ISSUE THREAD

**Issue by xabolcs** [yne/dzr#29]
## Deezer closes it's free service in some country. 

I got a mail from Deezer with subject "Deezer Free is ending 💔 But we have an offer!" and with content $subject, but without link to an official page which describes $subject in detail. :shrug: 

----

I hope your country is not involved and you don't archive this nice tool! :pray:

**Comment by yne** [comment]
I went to some country without free-tier support, yet `dzr` worked.

**Comment by xabolcs** [comment]
For the record:
After that date I get the following message after start listening music (in browser or in the (ported) [Electron](https://github.com/SibrenVasse/deezer) [apps](https://github.com/aunetx/deezer-linux):
> You can only listen to 30-second clips. Try Deezer Premium!

It looks like this:
> ![image](https://user-images.githubusercontent.com/568751/217074779-0d2fbfb7-6d63-4823-a40b-0d329e520dd4.png)

Thankfully, `dzr` works nicely as stated previously! Thanks @yne!
