### ISSUE TITLE
MacOS : bad DZR_CBC key extract

### ISSUE THREAD

**Issue by karawitan** [yne/dzr#30]
Hi ! 

  Many thanks for writing dzr and opening code looks very cool  !
I've installed successfully on mac, arl cookie automatically extracted, very cool feature.

Then, found some tracks, tried to play;

mpv is launched, that is good

```
master  ps -eaf | grep -i mpv
  502 98455 78800   0  6:03PM ttys007    0:00.00 grep -i mpv
  502 96551 96550   0  6:03PM ttys009    0:00.22 mpv -
```

But on the console I see:

```
[file] Reading from stdin...
Failed to recognize file format.

Exiting... (Errors when loading file)
```

Is there anything more to be tuned ?

**Comment by yne** [comment]
does it fail on all tracks ?

I dont have a mac to test :/

**Comment by karawitan** [comment]
Yes, seems to happen on all files.
Maybe that is because I have "high quality" setting ?

I tried to intercept the flow sent to mpv after decode, as you may see below.
file format does not seem to be mp3, don't know if it's normal ?

```
m1:dzr kalou$ git diff
diff --git a/dzr b/dzr
index 027de82..74abf4d 100755
--- a/dzr
+++ b/dzr
@@ -42,7 +42,7 @@ dzr_artist_0() { $DLG_LIST top?limit=50 '' albums '' fans '' related '' radio ''
 dzr_default()  { $FETCH -H "Accept-Language: $LANG" "$API$1" | jq "$FMT_LIST" | xargs $DLG_LIST @ "play all /track/" ;} # TODO: .next
 play() { # receive /track/1,2,3 from stdin
        xargs basename | xargs $0-url | while read url id; do
-               $FETCH "$url" | $0-dec $id | eval ${PLAYER:-'mpv -'} ;
+               $FETCH "$url" | $0-dec $id | tee /tmp/debug.mp3 | eval ${PLAYER:-'mpv -'} ;
        done
 }
 for url in "$@"; do

```

```
m1:dzr kalou$ file /tmp/debug.mp3
/tmp/debug.mp3: data
```

**Comment by karawitan** [comment]
Same issue on Linux / Kali

```
+ track_key=633565396f3b2262667120683d3c663c
+ stripe_size=2048
+ openssl_opt=-d -nopad -bufsize 2048 -K 633565396f3b2262667120683d3c663c -iv 0001020304050607
+ openssl bf-cbc -help
+ grep -q provider
+ openssl_opt=-d -nopad -bufsize 2048 -K 633565396f3b2262667120683d3c663c -iv 0001020304050607 -provider legacy
+ set -e
+ true
+ LC_ALL=POSIX dd bs=2048 count=1 status=none
+ openssl bf-cbc -d -nopad -bufsize 2048 -K 633565396f3b2262667120683d3c663c -iv 0001020304050607 -provider legacy
+ LC_ALL=POSIX dd bs=2048 count=2
+ grep -qe ^0[+]0
+ break
[file] Reading from stdin...
Failed to recognize file format.

Exiting... (Errors when loading file)
kalou@kali:~/dzr$ uname -a
Linux kali 6.1.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.12-1kali2 (2023-02-23) x86_64 GNU/Linux
```

**Comment by yne** [comment]
I suspect an invalid decryption stage (invalid decription key?)

do you have a working plateform you could compare with?

you should compare a the `tee` output before and after decryption on both platforms

**Comment by karawitan** [comment]
It's the first time I try dzr :) 
DZR_CBC is not set in my environment, and ~/.profile is not being updated by dzr

**Comment by karawitan** [comment]
Which platform is it "certified" to run ?

**Comment by samoht0** [comment]
> Which platform is it "certified" to run on ?

Not dzr "certified":
* Bitten apple "UNIX" stuff
* Linux distributions with wonky and unsafe custom openssl config: https://www.kali.org/docs/general-use/openssl-configuration/

So nearly everything Linux based  works. For example:
Arch, Fedora 36/37, Android using Termux, maybe even Kali with changed openssl "Strong Security" (read as: plain standard security) config.

**Comment by yne** [comment]
@karawitan can you confirm that
```bash
echo $DZR_CBC | sha1sum
```
return
```
2bccaaea1d9973189802dec476103aa20e7de95b
```
?

**Comment by yne** [comment]
your DZR_CBC shall be
- 16 chars long
- starting with `g`
- ending with `1`

can you post your value ? since its not the good one anyway.

try extract it again from another plateform.

**Comment by karawitan** [comment]
```
export DZR_CBC=x31x2Cx6ex2Cx66x2Cx7ax2Cx63x2Cx38x2Cx6cx2Cx34x61x2Cx39x2Cx76x2Cx3x2Cx77x2Cx35x2Cx65x2Cx67
```

**Comment by yne** [comment]
I don't know what kind of OS your are using but it work as expected even on barebone alpine
```
[yne@toaster ~]$ docker run -ti alpine
/ # apk add jq mpv dialog curl openssl
/ # wget -O- github.com/yne/dzr/archive/master.tar.gz | tar xzf -
/ # mv dzr-master/dzr* /usr/local/bin
/ # dzr
WARNING:
DZR_CBC variable is unset
extracting from web-player...
    echo "export DZR_CBC=g**************1" >> .profile
to avoid this warning
```

I even tested on kali, just like you
```
[yne@toaster ~]$ docker run -ti kalilinux/kali-last-release
┌──(root㉿5a5480d20205)-[/]
└─# apt update && apt install jq mpv dialog curl openssl
┌──(root㉿5a5480d20205)-[/]
└─# curl -L github.com/yne/dzr/archive/master.tar.gz | tar xzf -
┌──(root㉿5a5480d20205)-[/]
└─# mv dzr-master/dzr* /usr/local/bin
┌──(root㉿5a5480d20205)-[/]
└─# dzr
-e WARNING:
DZR_CBC variable is unset
extracting from web-player...
-e     echo "export DZR_CBC=g**************1" >> .profile
to avoid this warning
```
surprisingly the `echo` output an extra `-e` but the key is still correctly extracted

**Comment by yne** [comment]
@karawitan any update ?

**Comment by karawitan** [comment]
Hi ! here is the collection of evidences on m1 .. maybe jq implementation is different and causes different results ?

```
m1:dzr-master kalou$ type jq
jq is /opt/homebrew/bin/jq
m1:dzr-master kalou$ jq --version
jq-1.6

m1:dzr-master kalou$ export PATH=/bin:/usr/bin:/opt/homebrew/bin:/opt/local/bin
m1:dzr-master kalou$ env -i PATH=$PATH  ./dzr

(...)

ON:Object(D.a)(e),FORMATTED_NB_SONG:x?Object(u.a)(x.NB_SONG):0})}))}},[["7S06",1,0]]]);
//# sourceMappingURL=https://files.deezer.com/cache/js/app-web.c85a43e27575a3cb1679.js.map.json'
+ TMP_CBC='x61x2Cx39x2Cx76x2Cx3x2Cx77x2Cx35x2Cx65x2Cx67
x31x2Cx6ex2Cx66x2Cx7ax2Cx63x2Cx38x2Cx6cx2Cx34'
++ unscramble x61x2Cx39x2Cx76x2Cx3x2Cx77x2Cx35x2Cx65x2Cx67 x31x2Cx6ex2Cx66x2Cx7ax2Cx63x2Cx38x2Cx6cx2Cx34
++ printf x31x2Cx6ex2Cx66x2Cx7ax2Cx63x2Cx38x2Cx6cx2Cx34x61x2Cx39x2Cx76x2Cx3x2Cx77x2Cx35x2Cx65x2Cx67
+ export DZR_CBC=x31x2Cx6ex2Cx66x2Cx7ax2Cx63x2Cx38x2Cx6cx2Cx34x61x2Cx39x2Cx76x2Cx3x2Cx77x2Cx35x2Cx65x2Cx67
+ DZR_CBC=x31x2Cx6ex2Cx66x2Cx7ax2Cx63x2Cx38x2Cx6cx2Cx34x61x2Cx39x2Cx76x2Cx3x2Cx77x2Cx35x2Cx65x2Cx67
+ echo -e '    echo "export DZR_CBC=x31x2Cx6ex2Cx66x2Cx7ax2Cx63x2Cx38x2Cx6cx2Cx34x61x2Cx39x2Cx76x2Cx3x2Cx77x2Cx35x2Cx65x2Cx67" >> .profile\nto avoid this warning'
-e     echo "export DZR_CBC=x31x2Cx6ex2Cx66x2Cx7ax2Cx63x2Cx38x2Cx6cx2Cx34x61x2Cx39x2Cx76x2Cx3x2Cx77x2Cx35x2Cx65x2Cx67" >> .profile

(...)

# https://stedolan.github.io/jq
m1:dzr-master kalou$ jq --version
jq-1.6

m1:dzr-master kalou$ type openssl ; openssl version
openssl is hashed (/usr/bin/openssl)
LibreSSL 3.3.6
```

**Comment by yne** [comment]
okay, and the Linux distribution you ran was also on m1 ?

I suspected an endianess issue but it work on an armv7 android ...

I think the only solution is to compare with a working environment and find the culprit line/command.

**Comment by karawitan** [comment]
No, Kali on i386

**Comment by yne** [comment]
well, I also test on Intel+Kali and nothing strange happened...

does running the same kali docker command gives you an error ?

**Comment by karawitan** [comment]
The 2 docker commands give the same results as yours.

**Comment by yne** [comment]
thats a great new, so you find the culprit command now :)

maybe you don't use the same LOCALE between the native distribution and the docker one (see `env`) , or maybe different dependency version ?

**Comment by yne** [comment]
I can reproduce the key extraction bug on a MacBook M2 Pro of a friend.
I hope to have another debug session tomorrow.

**Comment by yne** [comment]
the issue is in the `xargs printf -0` part. macos seems to already escape the \x values during piping whether other POSIX OS don't ...

I'll think about a cross-platform solution.

**Comment by karawitan** [comment]
Ok great you found ! BTW: tested dzr on termux, works great !
