### ISSUE TITLE
provide vsix file in releases

### ISSUE THREAD

**Issue by coxackie** [yne/dzr#34]
Hi, I saw you added a VSCode extension. This is awesome! Are you going to submit to VSCode marketplace? At any rate, maybe you can also add a `vsix` file to the releases, so we can install it directly. Many thanks for considering!

**Comment by yne** [comment]
I manually added a VSIX in https://github.com/yne/dzr/releases/tag/230824
But I plan on doing this with Github Action
Also I created a Azure account but the uploaded VSIX was refused, I'll have to investigate why.

Any feedback are welcome

**Comment by yne** [comment]
I fixed the "undefined" bug
I also moved the queue to a side panel.
I'll publish soon.

there are some glitch that's I don't know how to fix (pressing DEL shall delete selected queue track, delete icon shall disappear when multiple track are selected etc.)
But it shall probably be good enough for another round of testing :)

**Comment by coxackie** [comment]
Thanks! It appears that the vsix file is missing from the assets.

**Comment by yne** [comment]
you can just zip the extension folder as zip and rename as vsix

https://github.com/yne/dzr/releases/tag/230827

**Comment by yne** [comment]
VSIX are now automatically built by Github Action at release.

Feel free to open another tickets if you have any feeedback/bugs in the extension

**Comment by coxackie** [comment]
many thanks for this. Very quickly: is the extension supposed to show album covers or something? There is an empty (in my case) square place in the middle of the Player tab. If this is planned for later, I will just wait, but if it is supposed to be already working I can open an issue.

**Comment by yne** [comment]
I published a new version with album cover fix

https://github.com/yne/dzr/commit/a3f8679f971cb277864552569b2d3a4a667b2eec#diff-e726dd4575ab638c7f3cc4079666e5d64dd60cd63abbae8abc12400767bea376R25

You shall find the new VSIX in release page in a second
