### ISSUE TITLE
[Help request] VS Code extension: application name in mixer

### ISSUE THREAD

**Issue by xabolcs** [yne/dzr#35]
Your VS Code extension is simply an awesome addition! Thanks! :pray: 

Sadly it shows up as "Chromium" in my mixer program and I'm so noob I don't even know where to start searching to report this: is this a VS Code limitation, is this an Electron limitation? Or something else?

![image](https://github.com/yne/dzr/assets/568751/1e695e8c-425c-4c72-a288-632a10872358)

Interestingly the MPRIS part looks good:

![image](https://github.com/yne/dzr/assets/568751/cba5a189-9a34-48b6-81ca-6e68d4dc3d5c)

----

Could you help me to point me to the right direction?

**Comment by yne** [comment]
I don't think I can change the process name, However I could change the player notification values

![image](https://github.com/yne/dzr/assets/5113053/721148a0-4887-4a08-b0db-d078ed756b57)

I could make the cover work. but neither youtube so it's probably another of those gnome issues. 

You can test: [extension.zip](https://github.com/yne/dzr/files/12456933/extension.zip)
(github only allow me to upload .zip so rename this .zip as .vsix)

**Comment by xabolcs** [comment]
Nice addition, will test soon! 💪

**Comment by coxackie** [comment]
Spotify managed to get the album cover correctly with gnome MPRIS, but it is not a very big deal, really. It works, and you can even go forward the queue. One cannot go so not backwards, but this may not be too weird at the moment, given that you cannot also do it in the extension.

**Comment by yne** [comment]
yeah I did not implemented the back tracking.

Do you have media keys on your keyboard (play/pause/next...) ? I wonder if those key also works now.

**Comment by xabolcs** [comment]
> Do you have media keys on your keyboard (play/pause/next...) ? I wonder if those key also works now.

I have those (play/pause/next) and all they work nicely now! :ok_hand:

**Comment by yne** [comment]
vsix published as 0.1.0
