### ISSUE TITLE
240406 is a wrong tag?

### ISSUE THREAD

**Issue by chenrui333** [yne/dzr#39]
👋 looks like 240406 tag the same commit as 231217, is that intentional? Thanks!

![image](https://github.com/yne/dzr/assets/1580956/3f86ce11-ca33-4d67-85f4-27450102ba78)

relates to https://github.com/Homebrew/homebrew-core/pull/168225

**Comment by yne** [comment]
yeah sorry about that.
I reverted this change

https://github.com/yne/dzr/pull/38

do you want the tag to ne removed ?

**Comment by chenrui333** [comment]
yeah, let's remove the tag, thanks!! (as it points to the same commit as 231217)

**Comment by yne** [comment]
Okay Done

**Comment by chenrui333** [comment]
Thanks @yne!
