### ISSUE TITLE
how to get DZR_AES key

### ISSUE THREAD

**Issue by icewyvrn** [yne/dzr#40]
I got DZR_CBC by following the wiki, but I have no idea how to get DZR_AES.

**Comment by yne** [comment]
dzr aes is only needed to find the URL of the MP3
but newer deezer api already give us the MP3 URL so we don't need it

I'll update the wiki

**Comment by icewyvrn** [comment]
> dzr aes is only needed to find the URL of the MP3
> but newer deezer api already give us the MP3 URL so we don't need it
> 
> What page/instructions required you to find it ?

I was using snap which is outdated

**Comment by yne** [comment]
yeah, if you know someone who might help on this that would be awesome
