### ISSUE TITLE
Termux Command on your project page does not work.

### ISSUE THREAD

**Issue by Whyme3** [yne/dzr#41]
I tried your command to install it on termux and didn't work but using this command did work and there was no need to use sudo. 

curl -sL github.com/yne/dzr/archive/master.tar.gz | tar xzf - mv dzr-master/dzr* /data/data/com.termux/files/usr/bin

**Comment by yne** [comment]
your command does not seems correct:

tar: mv: Not found in archive
tar: Exiting with failure status due to previous errors

**Comment by Whyme3** [comment]
I just just realized I did it in 2 commands and it worked and I combined them to be: curl -sL github.com/yne/dzr/archive/master.tar.gz | tar xzf - mv dzr-master/dzr* /data/data/com.termux/files/usr/bin 

But when I tried it again it didn't work you have to do it in 2 commands for some reason so to be correct it would be 
 1: curl -sL github.com/yne/dzr/archive/master.tar.gz | tar xzf - 
2: mv dzr-master/dzr* /data/data/com.termux/files/usr/bin

**Comment by yne** [comment]
I updated the README with the new instruction and used `$PREFIX/bin` which seems to be the more generic form.
