### ISSUE TITLE
DZR_API instruction

### ISSUE THREAD

**Issue by 89z** [yne/dzr#7]
I was able to find a somewhat easy way to get the Android key. I wont put the key here, but I thought this could be helpful to others. You can get the APK file here:

https://apps.evozi.com/apk-downloader?id=deezer.android.app

Extract the APK, then look inside `classes.dex` using this pattern:

~~~
[0-9A-Z]{64}
~~~

Another option is to get the Apple iOS app. You can get the IPA file here:

https://appdb.to/app/ios/292738169

However I would not recommend this as it is more difficult. To get the IPA file you need TOR, also the APK is only 27 MB while the IPA is 138 MB.

**Comment by yne** [comment]
Using
```bash
zipgrep -oa '[0-9A-Z]{64}' deezer.android.app_6210403_apps.evozi.com.apk classes.dex
```
I get ~10 matches
```
ZKKKKKKKKKKKKK...
N1157920892103...
N1157920892103...
39402006196394...
39402006196394...
4VCYIJUCDLOUEL...
68647976601306...
18554318339765...
68647976601306...
18554318339765...
```

I guess it's the 6th ?

**Comment by 89z** [comment]
Yes, I am working on a program to improve the process

**Comment by 89z** [comment]
Here is a better search, notice the extra `@`:

~~~
PS C:\> rg -a -o '@[0-9A-Z]{64}' classes.dex
62948:@4VCYIJUCDLOUEL...
~~~

**Comment by yne** [comment]
good catch, this one also work :

```
zipgrep -hoa '[0-9A-Z]{64}' deezer.android.app_6210403_apps.evozi.com.apk classes.dex | grep -Pv '[0-9]{63}' | grep -Pv '[A-Z]{64}'
```

it's a little bit long, I filter out the results with only number, and only letters

**Comment by yne** [comment]
@89z I linked the [wiki instructions](https://github.com/yne/dzr/wiki#DZR_API) to your first post (You can edit it if needed).

If that's okay for you, I'll let you close the issue.

**Comment by 89z** [comment]
looks good, thanks!
