### ISSUE TITLE
[Question] Getting the DZR_AES and DZR_CBC keys

### ISSUE THREAD

**Issue by freijon** [yne/dzr#9]
Hello

I'm trying to follow your instructions on the wiki for the AES and CBC keys. But I think I'm doing it wrong...
I found several `key` Uint8Arrays, but I think I know which one to decode. So I used an online JavaScript tool and ran `var final_text = key.map(e=>String.fromCharCode(e)).join('');` but the result is a 16 digit number with a lot of zeroes and only a few numbers other than zero. It doesn't look right...

And with the CBC I'm completely lost. I have no clue where I find these two arrays. The screenshot looks completely different than what I see on my Firefox Debugger.

Any help would be appreciated.

**Comment by yne** [comment]
Hi, they obfuscated the source even more.

Do you succeed if I ask you to

- search for `0x67]` or `[0x31` which are the start and end of the two 8 bytes parts of the CBC key
- re-assemble the key with: `[0x67, 0x34, 0x65 ... 0x61, 0x31].map(n=>String.fromCharCode(n)).join('')`

If you got it right I'll update the wiki with that much simpler instruction.

**Comment by yne** [comment]
I updated [the wiki](https://github.com/yne/dzr/wiki)

**Comment by freijon** [comment]
Sorry, I must have missed your response... I tried to search for 0x67] or [0x31 but I didn't find anything in the code. Maybe it's already outdated again?
